/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ClienteDAO;
import modelo.Deuda;
import modelo.DeudaDAO;
import modelo.Recibo;
import modelo.ReciboDAO;

/**
 *
 * @author Miguel
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    Cliente cl = new Cliente();
    ClienteDAO client = new ClienteDAO();
    Deuda dd = new Deuda();
    DeudaDAO deud = new DeudaDAO();
    DefaultTableModel modelo = new DefaultTableModel();
    Recibo rb = new Recibo();
    ReciboDAO recib = new ReciboDAO();
    
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnActualizar.setEnabled(false);
        deud.ConsultarCliente(cmbDNI);
        txtNombreDeuda.setEditable(false);
        recib.ConsultarCodigoCliente(cmbCClienteRecibo);
        recib.ConsultarMetodosDePago(cmbMetodos);
        int codigo = Integer.parseInt(cmbDeudaRecibo.getSelectedItem().toString());
        recib.SeleccionarMonto(codigo, txtDeudaRecibo);
        recib.ConsultarDocumento(cmbDocumentoRecibo);
    }
    
    public void ListarClientes(){
        List<Cliente> ListarCl = client.ListarClientes();
        modelo = (DefaultTableModel) TablaCliente.getModel();
        Object[] obj = new Object[5];
        for (int i = 0; i < ListarCl.size(); i++) {
            obj[0] = ListarCl.get(i).getId_cliente();
            obj[1] = ListarCl.get(i).getNombre();
            obj[2] = ListarCl.get(i).getDireccion();
            obj[3] = ListarCl.get(i).getTelefono();
            obj[4] = ListarCl.get(i).getEmail();
            modelo.addRow(obj);
        }
        TablaCliente.setModel(modelo);
    }
    
    public void ListarDeudas(){
        List<Deuda> ListarDd = deud.ListarDeuda();
        modelo = (DefaultTableModel) TablaDeudas.getModel();
        Object[] obj = new Object[3];
        for (int i = 0; i < ListarDd.size(); i++) {
            obj[0] = ListarDd.get(i).getId_deuda();
            obj[1] = ListarDd.get(i).getId_cliente();
            obj[2] = ListarDd.get(i).getMonto();
            modelo.addRow(obj);
        }
    }
    
    public void ListarRecibos(){
        List<Recibo> ListarRB = recib.ListarRecibos();
        modelo = (DefaultTableModel) TablaRecibos.getModel();
        Object[] obj = new Object[8];
        for (int i = 0; i < ListarRB.size(); i++) {
            obj[0] = ListarRB.get(i).getCodRecibo();
            obj[1] = ListarRB.get(i).getCodDeuda();
            obj[2] = ListarRB.get(i).getCodCliente();
            obj[3] = ListarRB.get(i).getCodDocumento();
            obj[4] = ListarRB.get(i).getCodTipoPago();
            obj[5] = ListarRB.get(i).getFecha();
            obj[6] = ListarRB.get(i).getFechaExp();
            obj[7] = ListarRB.get(i).getMonto();
            modelo.addRow(obj);
        }
    }
    
    public void LimpiarTabla(){
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        txtDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDeudas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoDeuda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMontoDeuda = new javax.swing.JTextField();
        txtNombreDeuda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbDNI = new javax.swing.JComboBox<>();
        btnGuardarDeuda = new javax.swing.JButton();
        btnEliminarDeuda = new javax.swing.JButton();
        btnLimpiarDeuda = new javax.swing.JButton();
        btnActualizarDeuda = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaRecibos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoRecibo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCodigoReciboDeuda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCodigoDocumento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtReciboFecha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtReciboFechaExpiracion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoTipoPago = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtReciboMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtFechaExpRecibo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbCClienteRecibo = new javax.swing.JComboBox<>();
        cmbDeudaRecibo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cmbMetodos = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtDeudaRecibo = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPagarRecibo = new javax.swing.JTextField();
        btnGuardarRecibo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnCalcularMonto = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtMontoRestanteRecibo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtDateRecibo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cmbDocumentoRecibo = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        btnImprimirR2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtImprimirCodigoRecibo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtImprimirNombre = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtImprimirDNI = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtImprimirFecha = new javax.swing.JTextField();
        txtImprimirDocumento = new javax.swing.JTextField();
        txtImprimirFormaPago = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtImprimirObservaciones = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        txtImprimirPago = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtImprimirPDF = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        txtImprimirCuenta = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnRecibos = new javax.swing.JButton();
        btnGenerarRecibo = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("THE SHOPPING");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DNI:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 55, -1, -1));

        TablaCliente.setForeground(new java.awt.Color(0, 0, 0));
        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Dirección", "Teléfono", "Email"
            }
        ));
        TablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCliente);
        if (TablaCliente.getColumnModel().getColumnCount() > 0) {
            TablaCliente.getColumnModel().getColumn(0).setHeaderValue("Código");
            TablaCliente.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            TablaCliente.getColumnModel().getColumn(2).setHeaderValue("Dirección");
            TablaCliente.getColumnModel().getColumn(3).setHeaderValue("Teléfono");
            TablaCliente.getColumnModel().getColumn(4).setHeaderValue("Email");
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 280));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        jPanel2.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 52, 146, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 89, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 86, 146, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 123, -1, -1));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 120, 146, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Teléfono:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 157, -1, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 154, 146, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 191, -1, -1));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 188, 146, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 263, 99, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 228, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 263, 84, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 228, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("DATOS DEL CLIENTE");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 15, -1, -1));

        jTabbedPane1.addTab("", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TablaDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Código Cliente", "Monto"
            }
        ));
        TablaDeudas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeudasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaDeudas);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Código");

        txtCodigoDeuda.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DNI Cliente");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Monto:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre");

        cmbDNI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------" }));
        cmbDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDNIActionPerformed(evt);
            }
        });

        btnGuardarDeuda.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardarDeuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarDeuda.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarDeuda.setText("GUARDAR");
        btnGuardarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDeudaActionPerformed(evt);
            }
        });

        btnEliminarDeuda.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminarDeuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarDeuda.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDeuda.setText("ELIMINAR");
        btnEliminarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDeudaActionPerformed(evt);
            }
        });

        btnLimpiarDeuda.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiarDeuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarDeuda.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarDeuda.setText("LIMPIAR");
        btnLimpiarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDeudaActionPerformed(evt);
            }
        });

        btnActualizarDeuda.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizarDeuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarDeuda.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarDeuda.setText("ACTUALIZAR");
        btnActualizarDeuda.setEnabled(false);
        btnActualizarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDeudaActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("DATOS DE LA DEUDA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarDeuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarDeuda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarDeuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarDeuda)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel39)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMontoDeuda, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNombreDeuda)
                                .addComponent(txtCodigoDeuda)
                                .addComponent(cmbDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCodigoDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNombreDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontoDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarDeuda)
                            .addComponent(btnActualizarDeuda))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarDeuda)
                            .addComponent(btnEliminarDeuda))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        TablaRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Recibo", "Cod Deuda", "Cod Cliente", "Cod Documento", "Cod Pago", "Fecha", "Fecha Exp", "Monto"
            }
        ));
        TablaRecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRecibosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaRecibos);

        jLabel11.setText("Cod. Recibo");

        jLabel12.setText("Cod. Deuda");

        jLabel13.setText("Cod. Cliente");

        jLabel14.setText("Cod. Documento");

        txtCodigoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDocumentoActionPerformed(evt);
            }
        });

        jLabel15.setText("Fecha");

        jLabel16.setText("Fecha Exp.");

        jLabel17.setText("Cod. Tipo Pago");

        jLabel19.setText("Monto");

        jButton1.setText("IMPRIMIR");

        jButton4.setText("LIMPIAR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtCodigoCliente)
                            .addComponent(txtCodigoReciboDeuda)
                            .addComponent(txtCodigoRecibo)
                            .addComponent(txtCodigoTipoPago)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReciboMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReciboFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReciboFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCodigoRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCodigoReciboDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtCodigoTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReciboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReciboFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReciboMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );

        jTabbedPane1.addTab("", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Código Deuda");

        txtFechaExpRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaExpReciboActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Fecha Expiración");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Código Cliente");

        cmbCClienteRecibo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------" }));
        cmbCClienteRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCClienteReciboActionPerformed(evt);
            }
        });

        cmbDeudaRecibo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        cmbDeudaRecibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDeudaReciboMouseClicked(evt);
            }
        });
        cmbDeudaRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeudaReciboActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Tipo de pago");

        cmbMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------" }));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Deuda");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Pago");

        btnGuardarRecibo.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardarRecibo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarRecibo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarRecibo.setText("GUARDAR");
        btnGuardarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarReciboActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LIMPIAR");

        btnCalcularMonto.setBackground(new java.awt.Color(0, 0, 0));
        btnCalcularMonto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcularMonto.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularMonto.setText("CALCULAR");
        btnCalcularMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMontoMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Monto restante");

        txtMontoRestanteRecibo.setEditable(false);
        txtMontoRestanteRecibo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Fecha");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Documento");

        cmbDocumentoRecibo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------" }));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("DATOS DEL RECIBO");

        btnImprimirR2.setBackground(new java.awt.Color(0, 0, 0));
        btnImprimirR2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnImprimirR2.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirR2.setText("IMPRIMIR");
        btnImprimirR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDeudaRecibo)
                    .addComponent(cmbDeudaRecibo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCClienteRecibo, javax.swing.GroupLayout.Alignment.LEADING, 0, 109, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDateRecibo)
                            .addComponent(cmbDocumentoRecibo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtFechaExpRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtPagarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26))
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoRestanteRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCalcularMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnImprimirR2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnGuardarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmbCClienteRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtDateRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtFechaExpRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDeudaRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(cmbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDocumentoRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeudaRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addComponent(txtMontoRestanteRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPagarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularMonto)
                    .addComponent(jButton3)
                    .addComponent(btnImprimirR2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnGuardarRecibo))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("CODIGO RECIBO");

        txtImprimirCodigoRecibo.setText("1035");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("NOMBRE CLIENTE");

        txtImprimirNombre.setText("Miguel");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("DNI CLIENTE");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("FECHA DE EXPIRACION");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("DOCUMENTO");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("FORMA DE PAGO");

        txtImprimirObservaciones.setColumns(20);
        txtImprimirObservaciones.setRows(5);
        txtImprimirObservaciones.setText("----------------");
        jScrollPane4.setViewportView(txtImprimirObservaciones);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("PAGO");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("OBSERVACIONES");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("IMPRIMIR RECIBO");

        txtImprimirPDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtImprimirPDF.setText("IMPRIMIR");
        txtImprimirPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImprimirPDFActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("CODIGO DEUDA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImprimirNombre)
                                    .addComponent(txtImprimirCodigoRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImprimirDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txtImprimirCuenta))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImprimirFecha)
                            .addComponent(txtImprimirDocumento)
                            .addComponent(txtImprimirFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImprimirPago, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addComponent(txtImprimirPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtImprimirCodigoRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtImprimirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtImprimirDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtImprimirCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtImprimirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtImprimirDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtImprimirFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtImprimirPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImprimirPDF)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("", jPanel6);

        btnCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("CLIENTES");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnPagos.setBackground(new java.awt.Color(0, 0, 0));
        btnPagos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(255, 255, 255));
        btnPagos.setText("DEUDAS");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        btnRecibos.setBackground(new java.awt.Color(0, 0, 0));
        btnRecibos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRecibos.setForeground(new java.awt.Color(255, 255, 255));
        btnRecibos.setText("RECIBOS");
        btnRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecibosActionPerformed(evt);
            }
        });

        btnGenerarRecibo.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerarRecibo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGenerarRecibo.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarRecibo.setText("NUEVO RECIBO");
        btnGenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReciboActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Urb. Las Malvinas - Cayma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecibos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagos)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecibos)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarRecibo)
                        .addGap(134, 134, 134))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(!"".equals(txtDNI.getText()) && !"".equals(txtNombre.getText()) && !"".equals(txtDireccion.getText()) && !"".equals(txtTelefono.getText()) && !"".equals(txtEmail.getText())){
            cl.setId_cliente(Integer.parseInt(txtDNI.getText()));
            cl.setNombre(txtNombre.getText());
            cl.setDireccion(txtDireccion.getText());
            cl.setTelefono(txtTelefono.getText());
            cl.setEmail(txtEmail.getText());
            client.RegistrarCliente(cl);
            LimpiarTabla();
            ListarClientes();
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
            LimpiarClientes();
        }else{
            JOptionPane.showMessageDialog(null, "Hay algun campo vacio");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarClientes();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void TablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClienteMouseClicked
        // TODO add your handling code here:
        int fila = TablaCliente.rowAtPoint(evt.getPoint());
        txtDNI.setText(TablaCliente.getValueAt(fila, 0).toString());
        txtNombre.setText(TablaCliente.getValueAt(fila, 1).toString());
        txtDireccion.setText(TablaCliente.getValueAt(fila, 2).toString());
        txtTelefono.setText(TablaCliente.getValueAt(fila, 3).toString());
        txtEmail.setText(TablaCliente.getValueAt(fila, 4).toString());
        txtDNI.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_TablaClienteMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtDNI.getText())) {
            int preguntar = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar al cliente?");
            if(preguntar == 0){
                int id = Integer.parseInt(txtDNI.getText());
                client.EliminarCliente(id);
                LimpiarTabla();
                ListarClientes();
                LimpiarClientes();
                btnGuardar.setEnabled(true);
                txtDNI.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        btnGuardar.setEnabled(true);
        txtDNI.setEnabled(true);
        LimpiarClientes();
        btnActualizar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if("".equals(txtDNI.getText())){
           JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }else{
            if(!"".equals(txtDNI.getText()) && !"".equals(txtNombre.getText()) && !"".equals(txtDireccion.getText()) && !"".equals(txtTelefono.getText()) && !"".equals(txtEmail.getText())){
                cl.setNombre(txtNombre.getText());
                cl.setDireccion(txtDireccion.getText());
                cl.setTelefono(txtTelefono.getText());
                cl.setEmail(txtEmail.getText());
                cl.setId_cliente(Integer.parseInt(txtDNI.getText()));
                client.ModificarCliente(cl);
                LimpiarTabla();
                LimpiarClientes();
                ListarClientes();
                txtDNI.setEnabled(true);
                btnGuardar.setEnabled(true);
                btnActualizar.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Hay algun campo vacio");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDeudaActionPerformed
        // TODO add your handling code here:
        if(!"".equals(cmbDNI != null) && !"".equals(txtMontoDeuda.getText())){
            dd.setId_cliente(Integer.parseInt(cmbDNI.getSelectedItem().toString()));
            dd.setMonto(Double.parseDouble(txtMontoDeuda.getText()));
            deud.RegistrarDeuda(dd);
            LimpiarTabla();
            ListarDeudas();
            JOptionPane.showMessageDialog(null, "Deuda Registrada");
        }else{
            JOptionPane.showMessageDialog(null, "Hay algun campo vacio");
        }
    }//GEN-LAST:event_btnGuardarDeudaActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarDeudas();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnPagosActionPerformed

    private void cmbDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDNIActionPerformed
        // TODO add your handling code here:
//        deud.ConsultarCliente(cmbDNI);
        String valor = cmbDNI.getSelectedItem().toString();
        deud.SeleccionarCliente(valor, txtNombreDeuda);
//        deud.ConsultarCliente(cmbDNI);
//        cmbDNI.removeAllItems();
//        deud.ConsultarCliente(cmbDNI);
    }//GEN-LAST:event_cmbDNIActionPerformed

    private void TablaDeudasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeudasMouseClicked
        // TODO add your handling code here:
        int fila = TablaDeudas.rowAtPoint(evt.getPoint());
        txtCodigoDeuda.setText(TablaDeudas.getValueAt(fila, 0).toString());
        cmbDNI.setSelectedItem(TablaDeudas.getValueAt(fila, 1).toString());
        txtMontoDeuda.setText(TablaDeudas.getValueAt(fila, 2).toString());
        cmbDNI.setEnabled(false);
        btnGuardarDeuda.setEnabled(false);
        btnActualizarDeuda.setEnabled(true);
    }//GEN-LAST:event_TablaDeudasMouseClicked

    private void btnLimpiarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDeudaActionPerformed
        // TODO add your handling code here:
        LimpiarDeuda();
        cmbDNI.setEnabled(true);
        btnGuardarDeuda.setEnabled(true);
        btnActualizarDeuda.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarDeudaActionPerformed

    private void btnEliminarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDeudaActionPerformed
        // TODO add your handling code here:
        if(!"".equals(txtCodigoDeuda.getText())){
            int preguntar = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar la deuda?");
            if(preguntar == 0){
                int id = Integer.parseInt(txtCodigoDeuda.getText());
                deud.EliminarDeuda(id);
                LimpiarTabla();
                ListarDeudas();
                LimpiarDeuda();
                btnGuardarDeuda.setEnabled(true);                
            }
        }
    }//GEN-LAST:event_btnEliminarDeudaActionPerformed

    private void btnActualizarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDeudaActionPerformed
        // TODO add your handling code here:
        if("".equals(txtCodigoDeuda.getText())){
            JOptionPane.showMessageDialog(null, "Seleccione una deuda");
        }else{
            if(!"".equals(txtMontoDeuda.getText())){
                dd.setMonto(Double.parseDouble(txtMontoDeuda.getText()));
                dd.setId_deuda(Integer.parseInt(txtCodigoDeuda.getText()));
                deud.ModificarDeuda(dd);
                LimpiarDeuda();
                LimpiarTabla();
                ListarDeudas();
            }else{
                JOptionPane.showMessageDialog(null, "El campo monto esta vacio");
            }
        }
    }//GEN-LAST:event_btnActualizarDeudaActionPerformed
//
    private void txtFechaExpReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaExpReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaExpReciboActionPerformed

    private void cmbCClienteReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCClienteReciboActionPerformed
        // TODO add your handling code here:
//        cmbDeudaRecibo.removeAllItems();
        cmbDeudaRecibo.removeAllItems();
        int valor = Integer.parseInt(cmbCClienteRecibo.getSelectedItem().toString());
        cmbDeudaRecibo.addItem("0");
        recib.ConsultarDeudas(valor, cmbDeudaRecibo);
//        cmbDeudaRecibo.removeAllItems();
    }//GEN-LAST:event_cmbCClienteReciboActionPerformed

    private void cmbDeudaReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeudaReciboActionPerformed
        // TODO add your handling code here:
        if(cmbDeudaRecibo.getSelectedItem() != null){
            
//            int valor = Integer.parseInt(cmbCClienteRecibo.getSelectedItem().toString());
//        
//            recib.ConsultarDeudas(valor, cmbDeudaRecibo);
            
            int codigo = Integer.parseInt(cmbDeudaRecibo.getSelectedItem().toString());
            recib.SeleccionarMonto(codigo, txtDeudaRecibo);
        }
//        int codigo = Integer.parseInt(cmbDeudaRecibo.getSelectedItem().toString());
//        recib.SeleccionarMonto(9, txtMontoRecibo);
    }//GEN-LAST:event_cmbDeudaReciboActionPerformed

    private void cmbDeudaReciboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDeudaReciboMouseClicked
        // TODO add your handling code here:
//        if(cmbDeudaRecibo.getSelectedItem() != null){
//            cmbDeudaRecibo.removeAllItems();
//            int valor = Integer.parseInt(cmbCClienteRecibo.getSelectedItem().toString());
//        
//            recib.ConsultarDeudas(valor, cmbDeudaRecibo);
//            int codigo = Integer.parseInt(cmbDeudaRecibo.getSelectedItem().toString());
//            recib.SeleccionarMonto(codigo, txtMontoRecibo);
//        }
    }//GEN-LAST:event_cmbDeudaReciboMouseClicked

    private void btnGenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReciboActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnGenerarReciboActionPerformed

    private void btnCalcularMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMontoMouseClicked
        // TODO add your handling code here:
        double monto = 0;
        if(!"".equals(txtPagarRecibo.getText())&& !"".equals(txtDeudaRecibo.getText())){
            monto = Double.parseDouble(txtDeudaRecibo.getText()) - Double.parseDouble(txtPagarRecibo.getText());
            txtMontoRestanteRecibo.setText(String.valueOf(monto));
        }else{
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }
    }//GEN-LAST:event_btnCalcularMontoMouseClicked

    private void btnGuardarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarReciboActionPerformed
        // TODO add your handling code here:
        int documento = 0;
        int metodo = 0;
        if(cmbDocumentoRecibo.getSelectedItem().equals("Servicio")){
            documento = 1;
        }else if(cmbDocumentoRecibo.getSelectedItem().equals("Producto")){
            documento = 2;
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de documento");
        }
        
        if(cmbMetodos.getSelectedItem().equals("Efectivo")){
            metodo = 1;
        }else if(cmbMetodos.getSelectedItem().equals("Tarjeta")){
            metodo = 2;
        }else if(cmbMetodos.getSelectedItem().equals("Yape")){
            metodo = 3;
        }else{
            JOptionPane.showMessageDialog(null, "Seleccuibe un metodo de pago");
        }
        
        if(cmbCClienteRecibo.getSelectedItem() != null && cmbDeudaRecibo.getSelectedItem() != null && !"".equals(txtDeudaRecibo.getText()) && !"".equals(txtDateRecibo.getText()) && cmbDocumentoRecibo.getSelectedItem() != null && !"".equals(txtPagarRecibo.getText()) && !"".equals(txtMontoRestanteRecibo.getText()) && !"".equals(txtFechaExpRecibo.getText()) && cmbMetodos.getSelectedItem() != null){
            rb.setCodDeuda(Integer.parseInt(cmbDeudaRecibo.getSelectedItem().toString()));
            rb.setCodCliente(Integer.parseInt(cmbCClienteRecibo.getSelectedItem().toString()));
            rb.setCodDocumento(documento);
            rb.setCodTipoPago(metodo);
            rb.setFecha(txtDateRecibo.getText());
            rb.setFechaExp(txtFechaExpRecibo.getText());
            rb.setMonto(Double.parseDouble(txtPagarRecibo.getText()));
            recib.RegistrarRecibo(rb);
            JOptionPane.showMessageDialog(null,"Recibo registrado");
        }else{
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }
    }//GEN-LAST:event_btnGuardarReciboActionPerformed

    private void txtCodigoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDocumentoActionPerformed

    private void btnRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecibosActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarRecibos();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnRecibosActionPerformed

    private void TablaRecibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRecibosMouseClicked
        // TODO add your handling code here:
        int fila = TablaRecibos.rowAtPoint(evt.getPoint());
        txtCodigoRecibo.setText(TablaRecibos.getValueAt(fila, 0).toString());
        txtCodigoReciboDeuda.setText(TablaRecibos.getValueAt(fila, 1).toString());
        txtCodigoCliente.setText(TablaRecibos.getValueAt(fila, 2).toString());
        txtCodigoDocumento.setText(TablaRecibos.getValueAt(fila, 3).toString());
        txtCodigoTipoPago.setText(TablaRecibos.getValueAt(fila, 4).toString());
        txtReciboFecha.setText(TablaRecibos.getValueAt(fila, 5).toString());
        txtReciboFechaExpiracion.setText(TablaRecibos.getValueAt(fila, 6).toString());
        txtReciboMonto.setText(TablaRecibos.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_TablaRecibosMouseClicked

    private void btnImprimirR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirR2ActionPerformed
        // TODO add your handling code here:
        txtImprimirFecha.setText(txtDateRecibo.getText());
        txtImprimirCuenta.setText(cmbDeudaRecibo.getSelectedItem().toString());
        txtImprimirDNI.setText(cmbCClienteRecibo.getSelectedItem().toString());
        txtImprimirDocumento.setText(cmbDocumentoRecibo.getSelectedItem().toString());
        txtImprimirFormaPago.setText(cmbMetodos.getSelectedItem().toString());
        txtImprimirPago.setText(txtPagarRecibo.getText());
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnImprimirR2ActionPerformed

    private void txtImprimirPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImprimirPDFActionPerformed
        // TODO add your handling code here:
        pdf();
    }//GEN-LAST:event_txtImprimirPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TablaDeudas;
    private javax.swing.JTable TablaRecibos;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarDeuda;
    private javax.swing.JButton btnCalcularMonto;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarDeuda;
    private javax.swing.JButton btnGenerarRecibo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarDeuda;
    private javax.swing.JButton btnGuardarRecibo;
    private javax.swing.JButton btnImprimirR2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarDeuda;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnRecibos;
    private javax.swing.JComboBox<String> cmbCClienteRecibo;
    private javax.swing.JComboBox<String> cmbDNI;
    private javax.swing.JComboBox<String> cmbDeudaRecibo;
    private javax.swing.JComboBox<String> cmbDocumentoRecibo;
    private javax.swing.JComboBox<String> cmbMetodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoDeuda;
    private javax.swing.JTextField txtCodigoDocumento;
    private javax.swing.JTextField txtCodigoRecibo;
    private javax.swing.JTextField txtCodigoReciboDeuda;
    private javax.swing.JTextField txtCodigoTipoPago;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDateRecibo;
    private javax.swing.JTextField txtDeudaRecibo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaExpRecibo;
    private javax.swing.JTextField txtImprimirCodigoRecibo;
    private javax.swing.JTextField txtImprimirCuenta;
    private javax.swing.JTextField txtImprimirDNI;
    private javax.swing.JTextField txtImprimirDocumento;
    private javax.swing.JTextField txtImprimirFecha;
    private javax.swing.JTextField txtImprimirFormaPago;
    private javax.swing.JTextField txtImprimirNombre;
    private javax.swing.JTextArea txtImprimirObservaciones;
    private javax.swing.JButton txtImprimirPDF;
    private javax.swing.JTextField txtImprimirPago;
    private javax.swing.JTextField txtMontoDeuda;
    private javax.swing.JTextField txtMontoRestanteRecibo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreDeuda;
    private javax.swing.JTextField txtPagarRecibo;
    private javax.swing.JTextField txtReciboFecha;
    private javax.swing.JTextField txtReciboFechaExpiracion;
    private javax.swing.JTextField txtReciboMonto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    private void LimpiarClientes(){
        txtDNI.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
    }
    
    private void LimpiarDeuda(){
        txtCodigoDeuda.setText("");
        cmbDNI.getSelectedItem();
        txtMontoDeuda.setText("");
        txtNombreDeuda.setText("");
    }
    
    private void pdf(){
        try {
            FileOutputStream archivo;
            File file = new File("src/PDF/recibo.pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/img/Logo-SIA.jpg");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.BOLD, BaseColor.BLACK);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Nro Recibo: " + txtImprimirCodigoRecibo.getText() + "\nFecha: " + new SimpleDateFormat("dd-mm-yy").format(date) + "\n\n");
            
            PdfPTable encabezado = new PdfPTable(4);
            encabezado.setWidthPercentage(100);
            encabezado.getDefaultCell().setBorder(0);
            float[] columnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            encabezado.setWidths(columnaEncabezado);
            encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
            encabezado.addCell(img);
            String ruc = "20555190132";
            String nom = "The Shopping";
            String tel = "(01) 641 8000";
            String dir = "Urb Las Malvinas - Cayma";
            
            encabezado.addCell("");
            encabezado.addCell("RUC " + ruc + "\n" + nom + "\nTelefono " + tel + "\nDireccion " + dir);
            encabezado.addCell(fecha);
            doc.add(encabezado);
            
            Paragraph cliente = new Paragraph();
            cliente.add(Chunk.NEWLINE);
            cliente.add("Datos del cliente:"+"\n\n");
            doc.add(cliente);
            
            PdfPTable tablacliente = new PdfPTable(4);
            tablacliente.setWidthPercentage(100);
            tablacliente.getDefaultCell().setBorder(0);
            float[] columnaCliente = new float[]{50f, 50f, 50f, 60f};
            tablacliente.setWidths(columnaCliente);
            tablacliente.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell dni = new PdfPCell(new Phrase("DNI: " , negrita));
            PdfPCell nombre = new PdfPCell(new Phrase("Nombre: " , negrita));
            PdfPCell deuda = new PdfPCell(new Phrase("Codigo Deuda: ", negrita ));
            PdfPCell fechaex = new PdfPCell(new Phrase("Fecha Expiracion: ", negrita ));
            dni.setBorder(0);
            nombre.setBorder(0);
            deuda.setBorder(0);
            fechaex.setBorder(0);
            tablacliente.addCell(dni);
            tablacliente.addCell(nombre);
            tablacliente.addCell(deuda);
            tablacliente.addCell(fechaex);
            tablacliente.addCell(txtImprimirDNI.getText());
            tablacliente.addCell(txtImprimirNombre.getText());
            tablacliente.addCell(txtImprimirCuenta.getText());
            tablacliente.addCell(txtImprimirFecha.getText());
            
            doc.add(tablacliente);
            
            // PAGO
            PdfPTable tablapago = new PdfPTable(4);
            tablapago.setWidthPercentage(100);
            tablapago.getDefaultCell().setBorder(0);
            float[] columnaPago = new float[]{50f, 50f, 50f, 60f};
            tablapago.setWidths(columnaPago);
            tablapago.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell observaciones = new PdfPCell(new Phrase("Observaciones: " , negrita));
            PdfPCell documentoP = new PdfPCell(new Phrase("Documento: " , negrita));
            PdfPCell metodo = new PdfPCell(new Phrase("Metodo de pago: " , negrita));
            PdfPCell montoPago = new PdfPCell(new Phrase("Monto pagado: " , negrita));
            observaciones.setBorder(0);
            documentoP.setBorder(0);
            metodo.setBorder(0);
            montoPago.setBorder(0);
            tablapago.addCell(observaciones);
            tablapago.addCell(documentoP);
            tablapago.addCell(metodo);
            tablapago.addCell(montoPago);
            tablapago.addCell(txtImprimirObservaciones.getText());
            tablapago.addCell(txtImprimirDocumento.getText());
            tablapago.addCell(txtImprimirFormaPago.getText());
            tablapago.addCell(txtImprimirPago.getText());
            
            doc.add(tablapago);
            
            doc.close();
            archivo.close();
        } catch (Exception e) {
        }
    }
}
